name: Docker build
on:
  push:
#    branches: [main, master]

  pull_request:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3


      -
        name: Login
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t $rev
          docker tag $rev 244530008913.dkr.ecr.eu-west-1.amazonaws.com/1026:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/1026:$rev